# Site settings
title: detachedhead
email: ptolemybarnes@gmail.com
description:
  detachedhead - the technical bloggings of ptolemy
url: "http://ptolemybarnes.github.io"
twitter_username: guacamolay
github_username:  ptolemybarnes

# Build settings
markdown: kramdown
